### ISSUE TITLE
localhost:25565 and other local servers can't be added

### ISSUE THREAD

**Issue by sybenx** [Player005/BetterAddServer#3]
>localhost:25565 

and other local servers such as those on a tailscale network: 
> myotherpc:25565 

cannot be added because the "Add Server" button is greyed out when these ips are used.

**Comment by Player005** [comment]
This is because currently, the name field does not get autofilled if the server address is only one word; if you manually put in a server name it should still work.
![grafik](https://github.com/Player005/BetterAddServer/assets/78274073/8862b1ba-8451-4832-9b5d-144435fc54f1)

I'm currently working on also filling in server name automatically even if the address is only one word

**Comment by Player005** [comment]
Fixed with latest release (1.0.2)
